version: '3'

services:
  s2:
    build: .
    depends_on:
      - redis
    environment:
      - redis=redis
    volumes:
      - .:/code
    command: /usr/local/bin/python /code/src/s2.py
  s3:
    build: .
    depends_on:
      - s2
      - redis
    environment:
      - redis=redis
    volumes:
      - .:/code
    command: /usr/local/bin/python /code/src/s3.py
  redis:
    image: "redis:alpine"
  web:
    build: ./web
    depends_on:
      - redis
    environment:
      - redis=redis
    ports:
      - "3000:3000"
    volumes:
      - ./web:/code
