version: '2'

services:
  redis:
    image: "redis:alpine"
  worker1:
    build: back
    depends_on:
      - redis
    environment:
      - redis=redis
    volumes:
      - ./back:/code
    command: /usr/local/bin/python /code/worker1.py
  worker2:
    build: back
    depends_on:
      - redis
    environment:
      - redis=redis
    volumes:
      - ./back:/code
    command: /usr/local/bin/python /code/worker2.py
  web:
    build: front
    depends_on:
      - redis
    environment:
      - redis=redis
    ports:
      - "3000:3000"
    volumes:
      - ./front:/code
